// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"repo.example.com/oss/internal/biz"
	"repo.example.com/oss/internal/conf"
	"repo.example.com/oss/internal/data"
	"repo.example.com/oss/internal/server"
	"repo.example.com/oss/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(env *conf.Env, confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMysqlCmd(bootstrap, logger)
	client := data.NewRedisClient(confData)
	ossClient, err := data.NewOssClient(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, db, client, logger, ossClient)
	if err != nil {
		return nil, nil, err
	}
	fileRepo := data.NewFileRepo(dataData, logger)
	fileUsecase := biz.NewFileUsecase(fileRepo, logger)
	fileService := service.NewFileService(fileUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, fileService, logger)
	httpServer := server.NewHTTPServer(bootstrap, confServer, fileService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
