// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.0--rc1
// source: oss/v1/oss.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OSS_GetOssStsToken_FullMethodName = "/file.v1.OSS/GetOssStsToken"
	OSS_UploadFile_FullMethodName     = "/file.v1.OSS/UploadFile"
)

// OSSClient is the client API for OSS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OSSClient interface {
	// 获取ossToken
	GetOssStsToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OssStsTokenResponse, error)
	// 文件上传
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
}

type oSSClient struct {
	cc grpc.ClientConnInterface
}

func NewOSSClient(cc grpc.ClientConnInterface) OSSClient {
	return &oSSClient{cc}
}

func (c *oSSClient) GetOssStsToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OssStsTokenResponse, error) {
	out := new(OssStsTokenResponse)
	err := c.cc.Invoke(ctx, OSS_GetOssStsToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oSSClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, OSS_UploadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OSSServer is the server API for OSS service.
// All implementations must embed UnimplementedOSSServer
// for forward compatibility
type OSSServer interface {
	// 获取ossToken
	GetOssStsToken(context.Context, *emptypb.Empty) (*OssStsTokenResponse, error)
	// 文件上传
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	mustEmbedUnimplementedOSSServer()
}

// UnimplementedOSSServer must be embedded to have forward compatible implementations.
type UnimplementedOSSServer struct {
}

func (UnimplementedOSSServer) GetOssStsToken(context.Context, *emptypb.Empty) (*OssStsTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOssStsToken not implemented")
}
func (UnimplementedOSSServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedOSSServer) mustEmbedUnimplementedOSSServer() {}

// UnsafeOSSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OSSServer will
// result in compilation errors.
type UnsafeOSSServer interface {
	mustEmbedUnimplementedOSSServer()
}

func RegisterOSSServer(s grpc.ServiceRegistrar, srv OSSServer) {
	s.RegisterService(&OSS_ServiceDesc, srv)
}

func _OSS_GetOssStsToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSSServer).GetOssStsToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OSS_GetOssStsToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSSServer).GetOssStsToken(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OSS_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OSSServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OSS_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OSSServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OSS_ServiceDesc is the grpc.ServiceDesc for OSS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OSS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file.v1.OSS",
	HandlerType: (*OSSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOssStsToken",
			Handler:    _OSS_GetOssStsToken_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _OSS_UploadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oss/v1/oss.proto",
}
